export * from './CategoryApi';
import { CategoryApi } from './CategoryApi';
export * from './OrderApi';
import { OrderApi } from './OrderApi';
export * from './OrderItemApi';
import { OrderItemApi } from './OrderItemApi';
export * from './ProductApi';
import { ProductApi } from './ProductApi';
export * from './StoreApi';
import { StoreApi } from './StoreApi';
export const APIS = [CategoryApi, OrderApi, OrderItemApi, ProductApi, StoreApi];
